### ISSUE TITLE
Code/Architectural Review

### ISSUE THREAD

**Issue by efaruk** [TitaniumSoft/yakari#3]
I know what I wrote and I know most of my mistakes (I were delayed some work, because I need to deliver something fast, you can see we have an idea ;) )

**Current Known Mistakes**:
1. Weak Loose Coupling
2. Used a Lot of Delegates
3. Exception Handling
4. Weak Thread Management

Note: We can make multiple reviews...

**Comment by Dirtypaws** [comment]
I think it would be really useful to generate a high level flow chart of how the library is going to work. That wouls help us understand what architectural improvements can be made.

Theres a free tool called Pencil Project that is helpful for generating quick mocks and flowcharts.

**Comment by efaruk** [comment]
Thanks Matt, i have created new issue  #6  and assigned to myself
