### ISSUE TITLE
Anouncement

### ISSUE THREAD

**Issue by efaruk** [TitaniumSoft/yakari#4]
I think we have a good idea. Distributed In Memory Cache (No More Serialization/Deserialization & Network Issues). But we need **more** attention. Yakari can be really popular in dotnet world...

Actually same idea can be applied java, c++, go, ruby, ... and many more. Because this is a good idea ;)

**Comment by funkydorian** [comment]
+1 actually solves the problems with centralised caches, especially during high load, which makes sense. CPU optimisation is also valuable.
